# -*- coding: utf-8 -*-
"""
Created on Sun Oct 24 10:31:24 2021

@author: Administrator
"""


# -- BACK TEST switch --

ATS_BACK_TEST_EN = 0

# ------------ Markets API URLs ------------
DYDX_API_HOST_MAINNET = 'https://api.dydx.exchange'


DYDX_API_HOST_ROPSTEN = 'https://api.stage.dydx.exchange'
# ------------ Ethereum Network IDs ------------
NETWORK_ID_MAINNET = 1
NETWORK_ID_ROPSTEN = 3

#RPC
RPC_ETH_PROVIDER_URL = 'https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161'
RPC_GANACHE_LOCALETH_PROVIDER_URL = 'http://localhost:8545'
RPC_ETH_ROPSTEN_PROVIDER_URL = 'https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161'


# ------------ Markets Symbol ------------

DYDX_BTC_USD = 'BTC-USD'
DYDX_ETH_USD = 'ETH-USD'
DYDX_LINK_USD = 'LINK-USD'
DYDX_AAVE_USD = 'AAVE-USD'
DYDX_UNI_USD = 'UNI-USD'
DYDX_SUSHI_USD = 'SUSHI-USD'
DYDX_SOL_USD = 'SOL-USD'
DYDX_YFI_USD = 'YFI-USD'
DYDX_ONEINCH_USD = '1INCH-USD'
DYDX_AVAX_USD = 'AVAX-USD'
DYDX_SNX_USD = 'SNX-USD'
DYDX_CRV_USD = 'CRV-USD'
DYDX_UMA_USD = 'UMA-USD'
DYDX_DOT_USD = 'DOT-USD'
DYDX_DOGE_USD = 'DOGE-USD'
DYDX_MATIC_USD = 'MATIC-USD'
DYDX_MKR_USD = 'MKR-USD'
DYDX_FIL_USD = 'FIL-USD'
DYDX_ADA_USD = 'ADA-USD'
DYDX_ATOM_USD = 'ATOM-USD'
DYDX_COMP_USD = 'COMP-USD'
DYDX_BCH_USD = 'BCH-USD'
DYDX_LTC_USD = 'LTC-USD'
DYDX_EOS_USD = 'EOS-USD'
DYDX_ALGO_USD = 'ALGO-USD'
DYDX_ZRX_USD = 'ZRX-USD'
DYDX_XMR_USD = 'XMR-USD'
DYDX_ZEC_USD = 'ZEC-USD'

#Freq
FREQ_1DAY="1DAY"
FREQ_4HOURS="4HOURS"
FREQ_1HOUR="1HOUR"
FREQ_30MINS="30MINS"
FREQ_15MINS="15MINS"
FREQ_5MINS="5MINS"
FREQ_1MIN="1MIN"

#---- Back Test
BT_FREQ_1M  = 60
BT_FREQ_5M  = 300
BT_FREQ_15M = 900
BT_FREQ_30M = 1800
BT_FREQ_1H  = 3600
BT_FREQ_4H  = 14400
BT_FREQ_1D  = 86400